stages:
 - docker

variables:
  IMAGE_NAME: "savood/nginx-well-known"

buildDocker:
  image: docker:latest
  services:
   - docker:dind
  stage: docker
  script:
   - docker info
   - docker build -t "$IMAGE_NAME:${CI_BUILD_REF}" -t "$IMAGE_NAME:latest" .
   - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASSWORD
   - docker push "$IMAGE_NAME:${CI_BUILD_REF}"
   - docker push "$IMAGE_NAME:latest"
  only:
   - master

buildDockerStaging:
  image: docker:latest
  services:
   - docker:dind
  stage: docker
  script:
   - docker info
   - docker build -t "$IMAGE_NAME:${CI_BUILD_REF}" .
   - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASSWORD
   - docker push "$IMAGE_NAME:${CI_BUILD_REF}"
  except:
   - master
